version: "3.7"
services:
  myos:
    container_name: '${NAME:-default}'
    image: 'rylandg/myos:${TAG:-latest}'
    tty: true
    volumes:
      -  "/var/run/docker.sock:/var/run/docker.sock"
      # Default copy all ssh config at home of local to remote
      -  "~/.ssh/:/home/ubuntu/.ssh"
      # Default copy all git config at home of local to remote
      -  "~/.gitconfig/:/home/ubuntu/.gitconfig"
      # Use project-local zsh, tmux and vim settings
      -  "./zsh/.zshenv:/home/ubuntu/.zshenv"
      -  "./zsh:/home/ubuntu/.zsh_config"
      -  "./tmux/tmux.conf:/home/ubuntu/.tmux.conf"                   
      -  "./tmux/tmux_saves:/home/ubuntu/.tmux_saves"
      -  "./vim:/home/ubuntu/.vim_runtime:delegated"
    ports:
      - "2222:22"
volumes:
  volume-name:
    driver: local
